name: CD - Production

on:
  push:
    branches:
      - production

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment: production-env
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: production-build
          path: build

      - name: Deploy to Production
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
