name: wf-ci-release

on:
  pull_request:
    branches:
      - "release/**"

jobs:
  ci-build-release-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}  

      - name: Lint HTML and CSS code
        run: |
          npx htmlhint "**/*.html"
          npx stylelint "**/*.css"
