name: wf-ci-release
on:
  pull_request:
    branches:
      -"release/**"
jobs:
  ci-build-release-job:
  runs-on: ubantu-latest
  steps:
    -name: checkout repo
     uses: actions/Checkout@v4
     with:
       ref: ${{github.ref}}
     -name: lint html and css code
      run: |
       npx htmlhint "**/*.html"
       npx stylelint "**/*.css"
      -name: test build
       run: |
        npx parcel build  "./src/index.html" --dist-dir "./dst" --public-url "./"