name: wf-deploy-production
on:
  push:
    branches:
      - production

jobs:
  build-production-job:
    runs-on: ubuntu-latest
    steps:
      - name: repo checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Build website
        run: npx parcel build "./src/index.html" --dist-dir "./production" --public-url "./"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with: 
          path: "./production"
          name: "build-artifact-production"

  deploy-production-job:
    needs: "build-production-job"
    environment: "production-env"
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy artifacts
        uses: actions/deploy-pages@v4
        with:
          artifact_name: "build-artifact-production"
          token: ${{ github.token }}
