name: wf-deploy-release
on:
  push:
    branches:
      - release

jobs:
  build-staging-job:
    runs-on: ubuntu-latest
    steps:
      - name: repo checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Build website
        run: npx parcel build "./src/index.html" --dist-dir "./staging" --public-url "./"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with: 
          path: "./staging"
          name: "build-artifact-staging"

  deploy-staging-job:
    needs: "build-staging-job"
    environment: "staging-env"
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy artifacts
        uses: actions/deploy-pages@v4
        with:
          artifact_name: "build-artifact-staging"
          token: ${{ github.token }}
